apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensuse-deployment
  labels:
    app: opensuse-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensuse-deployment
  template:
    metadata:
      labels:
        app: opensuse-deployment
    spec:
      containers:
      - name: opensuse
        image: registry.opensuse.org/opensuse/bci/bci-ci:3
        # We create a while loop to continually run sleep and ls.
        # This way we can detect two groups of processes in our test:
        # - process snapshot (bash)
        # - process events (sleep and ls).
        command: ["bash", "-c", "while true; do sleep 5; ls; done"]
