= RFC 0000: Template

[cols="<,<",]
|===
|Feature Name |++[++Name++]++
|Start Date |++[++Today++]++
|Category |++[++Category++]++
|RFC PR |++[++fill this in after opening PR++]++
|State |*ACCEPTED*
|===

== Summary

First RFC, which doubles as a template.

== Motivation

RFCs are a tool for achieving consensus, alignment, and documenting it for
reference.

When developing complex features that touch different parts of this project, it is
useful to have consensus on what the feature entails, its pros and cons, and how
the implementation will be achieved.

[[examples--user-stories]]
=== Examples / User Stories

See other RFCs.

== Detailed design

Adapt this template into a new RFC and open a PR against this repo.

An RFC is created with `ACCEPTED` as state. After discussion and adapting, if it
merges, it is merged as `ACCEPTED`. If it is finally rejected or consensus is
not reached, it is changed to `REJECTED` and merged.

States:

* `ACCEPTED`: Consensus exists on what to be done and how. Silence is not
agreement but unanimity is not needed either.
* `REJECTED`: No consensus either for the proposal or the implementation.

== Drawbacks

== Alternatives

== Unresolved questions
