= RFC 0002: Process Snapshot

[cols="<,<",]
|===
|Feature Name |Generate Process Snapshot using Tetragon
|Start Date |Sep. 9, 2025
|Category |Learner
|RFC PR |
|State |*ACCEPTED*
|===

== Summary

This RFC discusses how we generate a process snapshot of a node in our per-node component(daemon).

== Motivation

A process snapshot represents the current state of a protected environment, which includes PIDs, executable paths and their container metadata.

Although we can build the whole container profiles using only process events emitted by Tetragon, it takes time until all behavior is learned.

A process snapshot would provide what we need in order to address this issue.

There are several options to generate a process snapshot. This RFC is written to document these options and ensures that we have consensus in team.

[[examples--user-stories]]
=== Examples / User Stories

As a system admin, I'd like to learn container behavior without the need to restart my workload, for example, the hardened container with only the entrypoint executable.

== Detailed design

Instead of requiring `hostPID: true`, container runtime socket access, and other permissions, we rely on Tetragon's `FineGuidanceSensors` service and its `GetDebug` gRPC API.

`GetDebug` API returns all process information and their container metadata that have been cached inside Tetragon. With this, we can construct the process snapshot and trigger the behavior learning flow.

== Drawbacks

Without a process snapshot, for those containers with only one executable, we will not learn their behavior until the container restarts.

Note: Even with the process snapshot, we can't still catch behavior from an init container and the behavior when a container is starting. This is the limitation.

== Alternatives

=== Implement everything on our own

Many security softwares already do this, including neuvector. The flow is basically,

[arabic]
. Get all running process information using `hostPID: true` and root permission.
. Read each running process's `/proc/++<++pid++>++/cgroup` and find out its container ID.
. Query its container runtime's socket with the container ID and retrieve the process' container metadata.

Although it's technically possible to implement everything again, this does come with a few drawback:

* Extra privilege requirement and attack surface
** Having `hostPID: true` and root permission allows our component to read environment variables of all processes in the system, which is an attack surface for sensitive information.
** The ability to access container runtime socket is another attack surface for running unauthorized workload.
* Bigger test scope.
** There is no formal guideline to determine the container ID via `/proc/++<++pid++>++/cgroup`. It's all by convention.
** The test scope would include different high-level container runtimes (docker, containerd, or crio), low-level runtime (runc, crun or gvisor) and kubernetes flavors (k8s, OpenShift, k3s, kind, and more...)
* Inconsistent behavior with Tetragon.
** Because Tetragon does exactly the same thing, it makes it difficult to match Tetragon's behavior for each release.

[[get-process-snapshot-using-tetragonlog]]
=== Get Process Snapshot using tetragon.log

While the `GetDebug` API is used by the tetra CLI and is therefore considered stable enough, `GetDebug` is a debug API, so it may be subject to change if upstream maintainers decide to change it.

If this happens, we can move to `tetragon.log`.

Tetragon takes a snapshot of processes too while building its own process cache during startup. A few `PROCESS++_++EXEC` events with `procFS` flag set will be generated and left under `/var/run/cilium/tetragon/tetragon.log` in the host, so it's an alternative when `GetDebug()` API becomes not ideal. More information can be found here: https://tetragon.io/docs/reference/grpc-api/#process

== Unresolved questions
