= RFC 0003: Otel Log In E2E Tests

[cols="<,<",]
|===
|Feature Name |Retrieving otel traces in e2e tests
|Start Date |Sep. 10, 2025
|Category |e2e test
|RFC PR |++[++fill this in after opening PR++]++
|State |*ACCEPTED*
|===

== Summary

This RFC elaborates options how we analyze open telemetry (otel) traces sent by runtime enforcer in our e2e tests.

== Motivation

The runtime enforcer has a strong kernel dependency from Tetragon. Certain kernel build options or even a kernel bug could affect its functionality. Therefore, it's important to verify its behavior automatically. The current plan is to write an automatic test suite and run them in the targeted environment.

To ensure that monitor/protect events are generated/emitted correctly in the automatic test suite, we install an otel trace compatible component. Events will be sent to the component and retrieved for verification. This document will go through the design options in the following sections.

[[examples--user-stories]]
=== Examples / User Stories

As a developer/QA engineer, I want to make sure that events are correctly generated, emitted and exported in a given kubernetes environment.

== Detailed design

In order to access the events generated by runtime enforcer during test time, we install an open telemetry collector via http://open-telemetry.github.io/opentelemetry-helm-charts[its helm chart].

In addition to that, we further configure runtime enforcer to deliver the events to the otel collector via a k8s service: http://open-telemetry-collector-opentelemetry-collector.namespace.svc.cluster.local:4317 .

After that, we configure the otel collector to use file exporter, so we can access attributes in each span, where the detail of runtime enforcer's monitor/protect events will go to.

One key difference is that, we redirect the file output of the file exporter to `/dev/stdout`. Then we use https://github.com/kubernetes/client-go/blob/b1c7d7bb6258898f446036779f70f953ea01d312/kubernetes/typed/core/v1/pod_expansion.go#L44[GetLogs()] API with `Follow: true` (basically `kubectl logs -f`) in our test to receive events directly from the pod.

This method makes the e2e test platform-independent and can run in different kuberentes flavors.

Upon receiving the traces from otel collector, we parse them and verify if the behavior is as expected.

== Drawbacks

Without verifying the events generated, we can't be sure that an environment is fully supported until someone tests it.

== Alternatives

=== Write logs to a host file

https://github.com/kubewarden/policy-server/blob/2ad1de987d82e94d592e506721aa3c490cc025f6/tests/integration_test.rs#L961[kubewarden's policy server] runs otel collector in docker and makes it write traces into a host file.

A similar method could work with some tweaks.

* The otel collector have to run in the k8s cluster, so daemon can discover it in a platform-independent way.
* The otel collector writes the file to a host path.
* The e2e test then retrieves the log from the host.

However, even with these tweaks, accessing the log file is still challenging because it's platform-dependent. For example, on EKS and GKE, we would need a different method to access the log file from e2e test, which is less than ideal.

=== Rely on a out-of-cluster otel collector service

It would be platform-dependent to install a out-of-cluster service and allows the in-cluster runtime enforcer to connect to it.

=== Get the log via kubectl exec

The otel collector image is https://hub.docker.com/layers/otel/opentelemetry-collector/nightly/images/sha256-626de2d96f485d4b46c5b71d1acef0e68e987bc2b16b78db4d6c9889e2509e00[hardened] without shell and other access.

== Unresolved questions
